const teamLogos = {
  arizona_cardinals: "/logos/arizona_cardinals.png",
  atlanta_falcons: "/logos/atlanta_falcons.png",
  baltimore_ravens: "/logos/baltimore_ravens.png",
  buffalo_bills: "/logos/buffalo_bills.png",
  carolina_panthers: "/logos/carolina_panthers.png",
  chicago_bears: "/logos/chicago_bears.png",
  cincinnati_bengals: "/logos/cincinnati_bengals.png",
  cleveland_browns: "/logos/cleveland_browns.png",
  dallas_cowboys: "/logos/dallas_cowboys.png",
  denver_broncos: "/logos/denver_broncos.png",
  detroit_lions: "/logos/detroit_lions.png",
  green_bay_packers: "/logos/green_bay_packers.png",
  houston_texans: "/logos/houston_texans.png",
  indianapolis_colts: "/logos/indianapolis_colts.png",
  jacksonville_jaguars: "/logos/jacksonville_jaguars.png",
  kansas_city_chiefs: "/logos/kansas_city_chiefs.png",
  las_vegas_raiders: "/logos/las_vegas_raiders.png",
  los_angeles_chargers: "/logos/los_angeles_chargers.png",
  los_angeles_rams: "/logos/los_angeles_rams.png",
  miami_dolphins: "/logos/miami_dolphins.png",
  minnesota_vikings: "/logos/minnesota_vikings.png",
  new_england_patriots: "/logos/new_england_patriots.png",
  new_orleans_saints: "/logos/new_orleans_saints.png",
  new_york_giants: "/logos/new_york_giants.png",
  new_york_jets: "/logos/new_york_jets.png",
  philadelphia_eagles: "/logos/philadelphia_eagles.png",
  pittsburgh_steelers: "/logos/pittsburgh_steelers.png",
  san_francisco_49ers: "/logos/san_francisco_49ers.png",
  seattle_seahawks: "/logos/seattle_seahawks.png",
  tampa_bay_buccaneers: "/logos/tampa_bay_buccaneers.png",
  tennessee_titans: "/logos/tennessee_titans.png",
  washington_commanders: "/logos/washington_commanders.png"
};

export default teamLogos;